# Generated by Django 5.1.6 on 2025-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(),
        ),
    ]
