# Generated by Django 5.1.6 on 2025-02-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_remove_attendance_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='emp_id',
            new_name='employee',
        ),
    ]
