# Generated by Django 5.1.6 on 2025-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_employee_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.BinaryField(),
        ),
    ]
